;; DGO definition file for Awful Village level
;; We use the convention of having a longer DGO name for levels without precomputed visibility.

;; the actual file name still needs to be 8.3
("GLA.DGO"
 ("glacier.o"
  "villagep-obs.o"
  "linear-plat.o"
  "target-ice.o" ;; needed for ice physics
  "oracle.o"
  "battlecontroller.o"
  "citadel-part.o"
  "citadel-obs.o"
  "citb-plat.o"
  "citadel-sages.o"
  "snow-bunny.o"
  "citb-bunny.o"
  "citb-drop-plat.o"
  "assistant-citadel.o"
  "jungleb-obs.o"
  "bonelurker.o"
  "misty-obs.o"
  "misty-part.o"
  "misty-warehouse.o"
  "jungle-obs.o"
  "jungleb-obs.o"
  "jng-iris-door-ag.go"
  "silostep-ag.go"
  "rounddoor-ag.go"
  "mistycam-ag.go"
  "bonelurker-ag.go"
  "citadelcam-ag.go"
  "tpage-398.go"
  "tpage-400.go"
  "tpage-399.go"
  "tpage-401.go"
  "tpage-1470.go"
  "eggtop-ag.go"
  "water-anim-sunken-dark-eco-ag.go"
  "citb-coil-ag.go"
  "citb-generator-ag.go"
  "citb-hose-ag.go"
  "eichar-ice+0-ag.go" ;; needed for ice physics
  "plat-ag.go"
  "plat-eco-ag.go"
  "test-actor-ag.go"
  "babak-ag.go"
  "glacier.go"
  )
 )
